stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Build stage running..."

test_job:
  stage: test
  script:
    - echo "Test stage running..."

deploy_job:
  stage: deploy
  script:
    - echo "Deploy stage running..."
